version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/ryanfrench/aws-role
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/artifacts
      - run: make build
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - aws-role
      - store_artifacts:
          path: /tmp/artifacts
  test:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/ryanfrench/aws-role
    steps:
      - checkout
      - run: make test-junit
      - store_test_results:
          path: report.xml
  publish-release:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/ryanfrench/aws-role
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(artifacts/aws-role version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/artifacts
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test
      - publish-release:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
