version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.17
    working_directory: /go/src/github.com/ryanfrench/aws-auth
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: Install gox for cross-compiling
          command: go get -u github.com/mitchellh/gox
      - run:
          name: Build artifacts with gox for windows/linux amd64
          command: gox -osarch="linux/amd64 windows/amd64" -output "bin/{{.Dir}}"  ./...
      - persist_to_workspace:
          root: bin/
          paths:
            - aws-auth.exe
            - aws-auth
      - store_artifacts:
          path: bin/
  test:
    docker:
      - image: circleci/golang:1.17
    working_directory: /go/src/github.com/ryanfrench/aws-auth
    steps:
      - checkout
      - run: make test-junit
      - store_test_results:
          path: report.xml
  publish-release:
    docker:
      - image: circleci/golang:1.17
    working_directory: /go/src/github.com/ryanfrench/aws-auth
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(/tmp/artifacts/aws-auth version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/artifacts
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test
      - publish-release:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
