version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/ryanfrench/aws-role
    steps:
      - checkout
      - run: make build
  test:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/ryanfrench/aws-role
    steps:
      - checkout
      - run: make test-junit
      - store_test_results:
          path: report.xml
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test
